[versions]
okhttp = "4.12.0"
json = "20250517"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
json = { module = "org.json:json", version.ref = "json" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.6.0" }
